name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: 3.x
      - run: cmake
      - run: make VERBOSE=1
